export const APP_LOAD = 'APP_LOAD';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const MOVIE_PAGE_LOADED = 'MOVIE_PAGE_LOADED';
export const CREATE_MOVIE_PAGE_LOADED = 'CREATE_MOVIE_PAGE_LOADED';
export const CREATE_REVIEW_PAGE_LOADED = 'CREATE_REVIEW_PAGE_LOADED';
export const CREATE_SHOWTIME_PAGE_LOADED = 'CREATE_SHOWTIME_PAGE_LOADED';
export const SELECT_SEAT_PAGE_LOADED = 'SELECT_SEAT_PAGE_LOADED';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const ASYNC_START = 'ASYNC_START';
export const ASYNC_END = 'ASYNC_END';

export const CREATE_MOVIE = 'CREATE_MOVIE';
export const CREATE_REVIEW = 'CREATE_REVIEW';
export const CREATE_SHOWTIME = 'CREATE_SHOWTIME'
export const CREATE_BOOKINGS = 'CREATE_BOOKINGS';
export const DELETE_BOOKING = 'DELETE_BOOKING';
